apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    app: udagram-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-user
  template:
    metadata:
      labels:
        app: udagram-user
    spec:
      containers:
      - name: udagram-user
        image: qdockerfy/udagram-user
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: JWT_SECRET
        - name: URL
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: URL